/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mr.hadoop.wordcount;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WordCountTest {
    @Test
    void someLibraryMethodReturnsTrue() throws Exception {
        WordCountDriver.main(new String[2]);
        assertTrue(true);
    }
}
